//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Credit {
            get {
                object obj = ResourceManager.GetObject("Credit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CSearch {
            get {
                object obj = ResourceManager.GetObject("CSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CategoryList&quot;: {
        ///    &quot;1&quot;: {
        ///      &quot;Name&quot;: &quot;Pugilist&apos;s Arm&quot;,
        ///      &quot;Emoji&quot;: &quot;ðŸ¥Š&quot;
        ///    },
        ///    &quot;2&quot;: {
        ///      &quot;Name&quot;: &quot;Gladiator&apos;s Arm&quot;,
        ///      &quot;Emoji&quot;: &quot;ðŸ—¡ï¸&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;Name&quot;: &quot;Marauder&apos;s Arm&quot;,
        ///      &quot;Emoji&quot;: &quot;ðŸª“&quot;
        ///    },
        ///    &quot;4&quot;: {
        ///      &quot;Name&quot;: &quot;Archer&apos;s Arm&quot;,
        ///      &quot;Emoji&quot;: &quot;ðŸ¹&quot;
        ///    },
        ///    &quot;5&quot;: {
        ///      &quot;Name&quot;: &quot;Lancer&apos;s Arm&quot;,
        ///      &quot;Emoji&quot;: &quot;ðŸ”±&quot;
        ///    },
        ///    &quot;6&quot;: {
        ///      &quot;Name&quot;: &quot;One-handed Thaumaturge&apos;s Arm&quot;,
        ///      &quot;Emoji&quot;: &quot;:magic_wand:&quot;
        ///    },
        ///    &quot;7&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorWhite {
            get {
                object obj = ResourceManager.GetObject("ErrorWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;type&quot;:&quot;npc&quot;,&quot;id&quot;:&quot;1005665&quot;,&quot;obj&quot;:{&quot;i&quot;:1005665,&quot;n&quot;:&quot;Chocobo&quot;,&quot;l&quot;:54}},{&quot;type&quot;:&quot;npc&quot;,&quot;id&quot;:&quot;1006001&quot;,&quot;obj&quot;:{&quot;i&quot;:1006001,&quot;n&quot;:&quot;Chocobo&quot;,&quot;l&quot;:52,&quot;q&quot;:1}},{&quot;type&quot;:&quot;action&quot;,&quot;id&quot;:&quot;10401&quot;,&quot;obj&quot;:{&quot;i&quot;:10401,&quot;n&quot;:&quot;Chocobo Brush&quot;,&quot;c&quot;:61260,&quot;j&quot;:0,&quot;t&quot;:4,&quot;l&quot;:0}},{&quot;type&quot;:&quot;item&quot;,&quot;id&quot;:&quot;9784&quot;,&quot;obj&quot;:{&quot;i&quot;:9784,&quot;n&quot;:&quot;Chocobo Card&quot;,&quot;l&quot;:1,&quot;c&quot;:27662,&quot;t&quot;:86,&quot;g&quot;:14,&quot;r&quot;:1}},{&quot;type&quot;:&quot;item&quot;,&quot;id&quot;:&quot;30859&quot;,&quot;obj&quot;:{&quot;i&quot;:30859,&quot;n&quot;:&quot;Chocobo Carriage Whistle&quot;,&quot;l&quot;:1,&quot;c&quot;:26012,&quot;t&quot;:63,&quot;g&quot;:17,&quot;r&q....
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Job_AllRounder {
            get {
                object obj = ResourceManager.GetObject("Job_AllRounder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Achievements&quot;:null,&quot;AchievementsPublic&quot;:null,&quot;Character&quot;:{&quot;ActiveClassJob&quot;:{&quot;ClassID&quot;:3,&quot;ExpLevel&quot;:117310,&quot;ExpLevelMax&quot;:437600,&quot;ExpLevelTogo&quot;:320290,&quot;IsSpecialised&quot;:false,&quot;JobID&quot;:21,&quot;Level&quot;:46,&quot;Name&quot;:&quot;marauder \/ warrior&quot;,&quot;UnlockedState&quot;:{&quot;ID&quot;:21,&quot;Name&quot;:&quot;Warrior&quot;}},&quot;Avatar&quot;:&quot;https:\/\/img2.finalfantasyxiv.com\/f\/0afb42c62fb49a08c6c2aae7642ce19a_2e97c13fdd593d15d543093f8a37b6f0fc0_96x96.jpg?1635885630&quot;,&quot;Bio&quot;:&quot;-&quot;,&quot;ClassJobs&quot;:[{&quot;ClassID&quot;:1,&quot;ExpLevel&quot;:0,&quot;ExpLevelMax&quot;:0,&quot;ExpLevelTogo&quot;:0,&quot;IsSpecialised&quot;:false, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Moogle {
            get {
                object obj = ResourceManager.GetObject("Moogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProfileTemplate {
            get {
                object obj = ResourceManager.GetObject("ProfileTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsBlur {
            get {
                object obj = ResourceManager.GetObject("SettingsBlur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sidebar {
            get {
                object obj = ResourceManager.GetObject("Sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Topo {
            get {
                object obj = ResourceManager.GetObject("Topo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
